### PR TITLE
Add --dc-suffix to create subcommand

### PR DESCRIPTION
**Pull request by a1exsh**
This makes it consistent with `extend`.

### CODE REVIEW

**Comment by a1exsh** [comment]
:+1:

**Comment by slitsche** [comment]
I'd expect the value to be used in generate_taupage_user_data. But could not find it.

**Comment by a1exsh** [comment]
Not really, because that user data is a template, to which instance-specific details, such as volume name (which indeed depends on the `dc_suffix`), are added later:
https://github.com/zalando-stups/planb-cassandra/blob/master/planb/create_cluster.py#L496-L509

**Comment by a1exsh** [comment]
:+1:

**Comment by slitsche** [comment]
👍

**Pull request merged**
