### PR TITLE
Add --scalyr-region option to create and update cluster commands

### PR DESCRIPTION
**Pull request by a1exsh**
No default provided.

### CODE REVIEW

**Comment by a1exsh** [comment]
:+1:

**Comment by mastersimon** [comment]
Could you also update the readme.md. That would be great.

**Comment by a1exsh** [comment]
:+1:

**Comment by mastersimon** [comment]
Just tested it on our release environment. Works.

**Comment by a1exsh** [comment]
@mastersimon Could you give a +1 then? ;)

**Comment by mastersimon** [comment]
:+1:

**Comment by a1exsh** [comment]
Looks like it didn't count, but thanks for testing! :-)

**Comment by mastersimon** [comment]
:+1:

**Comment by mastersimon** [comment]
That is weird because in the [zappr file](https://github.com/zalando-stups/planb-cassandra/blob/master/.zappr.yaml) it says all from organization zalando.

**Comment by slitsche** [comment]
👍

**Pull request merged**
