### PR TITLE
Update Dockerfile curl calls to use new URL and fail safer

### PR DESCRIPTION
**Pull request by john-coleman**
Fixes https://github.com/zalando-stups/planb-cassandra/issues/243

* Previous `https://www.apache.org/dist/cassandra/KEYS` URL is a 302 redirect that is not being follows by `curl`
* This was causing errors from `apt-key` such as:
  * `Warning: apt-key output should not be parsed (stdout is not a terminal)`
  * `gpg: no valid OpenPGP data found.`

### CODE REVIEW

**Comment by a1exsh** [comment]
The current version of the download instructions page says use `https://downloads.apache.org/cassandra/KEYS`:
https://cassandra.apache.org/download/

```
curl -I https://downloads.apache.org/cassandra/KEYS
HTTP/1.1 200 OK
Date: Tue, 07 Jul 2020 10:28:34 GMT
Server: Apache
Last-Modified: Thu, 26 Mar 2020 18:13:43 GMT
ETag: "3f242-5a1c5f1f8fdfe"
Accept-Ranges: bytes
Content-Length: 258626
Access-Control-Allow-Origin: *
```

Doesn't need a redirect.  Let's use this one?

**Comment by a1exsh** [comment]
@john-coleman thanks.  Can we drop the follow redirect flags?  Doesn't leave me with a good warm feeling when downloading signature keys.

**Comment by john-coleman** [comment]
sure

**Comment by a1exsh** [comment]
:+1:

**Comment by john-coleman** [comment]
👍

**Comment by slitsche** [comment]
:+1:

**Pull request merged**
